[tool.poetry]
name = "packman"
version = "0.1.0"
description = ""
authors = ["Dmytro Furzenko <dimonji@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
